"""Markdown output formatter."""

from pathlib import Path
from datetime import datetime

from blog_generator.generator.claude import BlogDraft
from blog_generator.fetcher.github import Release


class MarkdownFormatter:
    @staticmethod
    def save(draft: BlogDraft, release: Release, output_path: Path) -> None:
        """Save blog as markdown file."""
        content = f"""# {draft.title}

> **版本**: {release.tag_name}
> **发布日期**: {release.published_at[:10]}
> **标签**: {', '.join(draft.tags)}

## 摘要

{draft.summary}

---

{draft.content}

---

*Generated by vLLM-Omni Blog Generator at {datetime.now().isoformat()}*
"""
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(content)
